name: dsci-575-mkc-yho
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets
  - jupyterlab
  - faiss
  - pandas
  - nltk
  - pip
  - pip:
      - langchain
      - langchain-core
      - langchain-community
      - langchain-huggingface
      - langchain-openai
      - rank-bm25
      - sentence-transformers
      - python-dotenv
      - streamlit