name: 575_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - ipykernel
  - jupyterlab
  - pandas
  - nltk
  - pip
  - pip:
      - langchain-core
      - rank-bm25
      - sentence-transformers
      - python-dotenv
